### PR TITLE
Add showcase gif for functionality

### PR DESCRIPTION
**Pull request by Stronkness**
Used asciinema to record when i do `git fork` and `git rename-branch`. Changed to gif format and speed up to 200%

Tested on local branch

Link to gif changed to gitapper repo. Might not wok until merge.

### CODE REVIEW

**Comment by Stronkness** [comment]
Solves #9

**Comment by Mte90** [comment]
I think that in the meantime is fine but  it's the case to show the git fork command with a forked repo as in this gif there is just an error.

**Comment by Stronkness** [comment]
No it works. The error is just that git doesnt recognise the command. But as shown in the gif it works to fork it. I show the content before and after the fork

**Comment by Stronkness** [comment]
The printouts in pre-fork also happends

**Comment by Stronkness** [comment]
Note: I can try in the future to do a better gif showing your project

**Pull request merged**
